#! /bin/sh

sxhkd &
setxkbmap -option terminate:ctrl_alt_bksp &
setxkbmap gb &
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true

bspc rule -a Xterm:ranger desktop='^3'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a Xterm:neomutt desktop='^2'
bspc rule -a chromium desktop='^1'
xterm -c scratchpad &
bspc rule -a scratchpad sticky=on state=floating hidden=on
pgrep -x panel > /dev/null || panel &
