#! /bin/sh

sxhkd &
setxkbmap -option terminate:ctrl_alt_bksp &
setxkbmap gb &
bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config border_radius        8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a qutebrowser desktop='^1'
bspc rule -a firefox-developer-edition='^1'
bspc rule -a ranger desktop='^3'
bspc rule -a neomutt desktop='^2'
bspc rule -a mplayer2 state=floating
st -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on 
panel &
